### ISSUE TITLE
发生闪退的处理方式

### ISSUE THREAD

**Issue by martjay** [Quandong-Zhang/easynet-playlist-downloader#1]
如题

**Comment by FlorenceZh** [comment]
根据经验，我猜测可能有以下三种情况：
1.若运行源码，请根据import配置好依赖项(除import的外还需ffmpeg，必位于PATH或同一目录下)，若运行的是编译好的release，则无须注意。
2.若使用科学上网代理，请现在使用前解除系统代理。
3.还希望你使用[最新的release](https://github.com/Quandong-Zhang/easynet-playlist-downloader/releases/tag/V1.0.2)，刚刚fix了很多bug，或许这个也许也可以解决你的问题。
**若检查以上三点后问题依然出现，请附上日志，环境，报错内容<br>
没有这些我无法准确的确定问题所在。**<br>
祝好

**Comment by martjay** [comment]
> 根据经验，我猜测可能有以下三种情况： 1.若运行源码，请根据import配置好依赖项(除import的外还需ffmpeg，必位于PATH或同一目录下)，若运行的是编译好的release，则无须注意。 2.若使用科学上网代理，请现在使用前解除系统代理。 3.还希望你使用[最新的release](https://github.com/Quandong-Zhang/easynet-playlist-downloader/releases/tag/V1.0.2)，刚刚fix了很多bug，或许这个也许也可以解决你的问题。 **若检查以上三点后问题依然出现，请附上日志，环境，报错内容 没有这些我无法准确的确定问题所在。** 祝好

用了新版，确实可以下载了谢谢咯，但是会有一些提示“你大概是没登陆或者缺少钞能力”，如果能破就好了

**Comment by FlorenceZh** [comment]
> > 根据经验，我猜测可能有以下三种情况： 1.若运行源码，请根据import配置好依赖项(除import的外还需ffmpeg，必位于PATH或同一目录下)，若运行的是编译好的release，则无须注意。 2.若使用科学上网代理，请现在使用前解除系统代理。 3.还希望你使用[最新的release](https://github.com/Quandong-Zhang/easynet-playlist-downloader/releases/tag/V1.0.2)，刚刚fix了很多bug，或许这个也许也可以解决你的问题。 **若检查以上三点后问题依然出现，请附上日志，环境，报错内容 没有这些我无法准确的确定问题所在。** 祝好
> 
> 用了新版，确实可以下载了谢谢咯，但是会有一些提示“你大概是没登陆或者缺少钞能力”，如果能破就好了

哈哈,这个问题其实可以解决,但是需要一个有VIP播放权限的账户做api代理.
本人学生党,穷酸的很,所以暂时木的办法.
不过你可以尝试修改源码的[登录配置](https://github.com/Quandong-Zhang/easynet-playlist-downloader/blob/main/main.py#L37),登录到一个有VIP播放权限的账户,这样应该就可以了(笑

**Comment by martjay** [comment]
> > > 根据经验，我猜测可能有以下三种情况： 1.若运行源码，请根据import配置好依赖项(除import的外还需ffmpeg，必位于PATH或同一目录下)，若运行的是编译好的release，则无须注意。 2.若使用科学上网代理，请现在使用前解除系统代理。 3.还希望你使用[最新的release](https://github.com/Quandong-Zhang/easynet-playlist-downloader/releases/tag/V1.0.2)，刚刚fix了很多bug，或许这个也许也可以解决你的问题。 **若检查以上三点后问题依然出现，请附上日志，环境，报错内容 没有这些我无法准确的确定问题所在。** 祝好
> > 
> > 
> > 用了新版，确实可以下载了谢谢咯，但是会有一些提示“你大概是没登陆或者缺少钞能力”，如果能破就好了
> 
> 哈哈,这个问题其实可以解决,但是需要一个有VIP播放权限的账户做api代理. 本人学生党,穷酸的很,所以暂时木的办法. 不过你可以尝试修改源码的[登录配置](https://github.com/Quandong-Zhang/easynet-playlist-downloader/blob/main/main.py#L37),登录到一个有VIP播放权限的账户,这样应该就可以了(笑

好吧
